# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult.xci
# IP: The module: 'super_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'super_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult.xci
# IP: The module: 'super_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'super_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
