# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.cache/wt [current_project]
set_property parent.project_path C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo c:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/Lab/Desktop/Gengchen_stuff/unif_input.dat
read_verilog -library xil_defaultlib C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/new/gng_top.v
read_ip -quiet C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult.xci
set_property used_in_implementation false [get_files -all c:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult_ooc.xdc]
set_property is_locked true [get_files C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/sources_1/ip/super_mult/super_mult.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/constrs_1/new/gaus.xdc
set_property used_in_implementation false [get_files C:/Users/Lab/Desktop/Gengchen_stuff/super_gaus_noise/super_gaus_noise.srcs/constrs_1/new/gaus.xdc]


synth_design -top gng_top -part xc7vx690tffg1761-2


write_checkpoint -force -noxdef gng_top.dcp

catch { report_utilization -file gng_top_utilization_synth.rpt -pb gng_top_utilization_synth.pb }
